### ISSUE TITLE
parse youtube https:// urls

### ISSUE THREAD

**Issue by ghost** [zaius/youtube_playlist#1]
Hi! thanks for the really nice tool. 
My problem is that your js script at https://github.com/zaius/youtube_playlist/raw/master/youtube_playlist.min.js (I use the bookmarklet) only searches the page for `href^="http://www.youtube"` links, an then ignores `href^="https:` llinks. I have bookmark pages full of these, none of the linked youtube videos are put in the playlist.

I have replaced `href^="https://www.youtube` with `href^="https://www.youtube` in the script and it works as expected, except it doesn't parses plain http links anymore. Is there a way to make it parse 
_both_ (http and https) links?

Thanks

**Comment by zaius** [comment]
Done! jQuery's attribute selectors don't allow regexes, so I changed it over to a fiter, and hopefully it should work on both http and https videos now.

I also probably need to check for youtube shortened URLs too, such as http://youtu.be/video_id. Let me know if that's causing problems and I'll fix it up.

**Comment by ghost** [comment]
Hi, good to see you working on this again! It works for me now, and I personally don't care about shortened urls at the moment ( I have a shell script to un-shorten urls), though that might be useful. Thanks!
