### ISSUE TITLE
"next" link not working

### ISSUE THREAD

**Issue by ghost** [zaius/youtube_playlist#3]
Hi again, the "next" link at the bottom of the video frame does not work for me. Tested it on your page at http://zaius.github.com/youtube_playlist/ and some youtube bookmarks pages I own.

Firefox 17.0 on Windows at the moment, may test it on other browsers/OSs if you want me to.

**Comment by zaius** [comment]
Can you open up the developer console and let me know if you're getting any errors?

I've only tested it on my machine so far, but it's working on chrome and firefox on mac. I'll try get access to a windows machine and see what's going on.

**Comment by ghost** [comment]
Looks like it depends on the page. Does it work for you there? http://telecom.dmz.se/links/?searchtags=music

I have no problems on https://pay.reddit.com/r/ElectronicJazz/ for example. But it won't work on the first page I linked.

**Comment by zaius** [comment]
Yep that first page works fine for me on both firefox and chrome on mac. I'll let you know as soon as I can try on windows.

**Comment by ghost** [comment]
Just tested on Firefox 17 on Linux (Debian). Same results as in my previous comment, here is what I get in the console when clicking the "next" link:

```
-- [00:33:22,375] TypeError: y.loadVideoById is not a function @ http://github.com/zaius/youtube_playlist/raw/master/youtube_playlist.min.js:1
```

This is the error I get on my Linux laptop. May test again on windows

**Comment by ghost** [comment]
For some reason it works now. Firefox 19 on Debian, on the page I linked earlier.
Thanks for the work you've put into this, congrats

**Comment by zaius** [comment]
Great! I put some time into it but couldn't reproduce it, so good to hear it's working again. Thanks for taking the time to update the report.
