### ISSUE TITLE
Add support for Vimeo, Soundcloud

### ISSUE THREAD

**Issue by nodiscc** [zaius/youtube_playlist#4]
Hi, thanks again for writing this. I use it daily as a kind of webradio player (run it on [this page](http://www.reddit.com/r/electronicjazz+Cyberpunk_Music+blues+boardsofcanada+futurebeats+jazz+jazznoir+MusicForConcentration+electronicblues) - endless music discovery!).

How add would it be to add support for more sites? I was mainly thinking about http://soundcloud.com and http://vimeo.com. If it could be extended to support as many sites as [youtube-dl](https://github.com/rg3/youtube-dl/tree/master/youtube_dl/extractor) it would be great, although that would certainly be a huge amount of work. Those 2 sites only would make my day.

What do you think?

**Comment by zaius** [comment]
Great to hear this is still getting some use! The youtube-dl project you linked is in python and can't be run inside the browser, so unfortunately it's not an easy copy and paste to get things working.

That said, both vimeo and soundcloud now have javascript controllable APIs, so it would be possible to implement a player that handles all of them. I don't think I have enough free time to add that in right now, but pull requests are definitely welcome.

**Comment by MBybee** [comment]
I just now discovered this, and it's AWESOME. I'd love to see a soundcloud one, if you do end up having a chance.

**Comment by nodiscc** [comment]
Unmaintained project, closing.
